//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.YoloInterface
{
    [Serializable]
    public class YoloMsg : Message
    {
        public const string k_RosMessageName = "yolo_interface/Yolo";
        public override string RosMessageName => k_RosMessageName;

        public byte detections;
        //  number of detections

        public YoloMsg()
        {
            this.detections = 0;
        }

        public YoloMsg(byte detections)
        {
            this.detections = detections;
        }

        public static YoloMsg Deserialize(MessageDeserializer deserializer) => new YoloMsg(deserializer);

        private YoloMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.detections);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.detections);
        }

        public override string ToString()
        {
            return "YoloMsg: " +
            "\ndetections: " + detections.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
